### ISSUE TITLE
Short code not working

### ISSUE THREAD

**Issue by clas-web** [cbarto11/d3-word-cloud-widget#5]
Short code for inserting a tag cloud into a post recently stopped working, see:
https://clas-pages.uncc.edu/inss-members/

Here is short code:
[d3-word-cloud title=" " post-types="post" taxonomies="category" minimum-count="1" maximum-words="250" orientation="horizontal" font-family="Georgia" font-size="14,60" font-color="#CCCCCC, #003366,#000000" canvas-size="675,450"]

Not sure when this tag cloud stopped working.  Changes that have occurred since last working may have been update of WordPress codebase to 4.0.1

**Comment by marpa** [comment]
This issue can be debugged on development server, see:
https://clas-incubator-wp.uncc.edu/inss-members/

**Comment by cbarto11** [comment]
The reason the shortcode is not working is due to the shortcode.  For example, the current preg_match is this regex: `font-size=\"([^\"]+)\"`, but needed to be `font-size=[”″\"]([^″”\"]+)[”″\"]` in order to match your code.

**Comment by cbarto11** [comment]
5d4f098337e336590595af4870430e53c4238545

Decreasing "the_content" filter order to 1 seems to fix it.
