### ISSUE TITLE
Enable word clouds of a filtered set of taxonomy terms

### ISSUE THREAD

**Issue by marpa** [cbarto11/d3-word-cloud-widget#6]
Add options to specify a specific parent taxonomy term and then display only terms that are included in posts the children of the specified parent term.

For example if you specify "anthropology" as a parent category and chose to display the "tag" taxonomy, then the cloud should show only the tags on posts that are in the "anthropology" category

**Comment by cbarto11** [comment]
aad51a6c737131cb4c4e9f6ed9173069fffa5d58
