### ISSUE TITLE
Filtered attribute not returning all items

### ISSUE THREAD

**Issue by marpa** [cbarto11/d3-word-cloud-widget#7]
Word clouds that are filtered do not seem to display all of the terms that they should, see:
https://clasconnections.uncc.edu/department/languages-and-culture-studies/

This word cloud is set to filterby="connection-group:languages-and-culture-studies"

However there are many research items in this connection-group that are NOT displayed in the word cloud even though:
minimum_count="0" 
maximum_words="500"

**Comment by cbarto11** [comment]
5b3266d272845e6c5b72bc7e4e456dfbcf48a86b
